#Conditional Statement

In [1]:
if True:
    print('Hey Buddy')

Hey Buddy


In [3]:
if true:
    print('hi')

NameError: name 'true' is not defined

In [4]:
if True:
print('hello')

IndentationError: expected an indented block after 'if' statement on line 1 (1785633973.py, line 2)

In [6]:
if True:                  #after this statement 4 space required
 print('hello')

hello


In [8]:
if True:
    print('Data science')

Data science


In [10]:
if False:
    print('Data science')
print('bye bye for now')

bye bye for now


In [11]:
if True:
    print('Data science')
print('bye bye for now')

Data science
bye bye for now


In [12]:
if True:
    print('Data science')
else:
    print('bye bye for now')

Data science


In [13]:
if False:
    print('Data science')
else:
    print('bye bye for now')

bye bye for now


In [14]:
x=4
r=x%2

if r==0:
    print('Even Number')

Even Number


In [18]:
x=5
r=x%2

if r==0:
    print('Even Number')

In [20]:
x=5
r=x%2

if r==0:
    print('Even Number')
else:
    print('Odd Number')

Odd Number


In [21]:
x=418648
r=x%2

if r==0:
    print('Even Number')
else:
    print('Odd Number')

Even Number


In [22]:
x=4
r=x%2

if r==0:
    print('Even Number')
if r==1:
    print('Odd Number')
if r==2:
     print('even number')
    

Even Number


In [23]:
x=5
r=x%2

if r==0:
    print('Even Number')
if r==1:
    print('Odd Number')
if r==2:
     print('even number')
    

Odd Number


In [24]:
x=1

if x==1:
    print('one')
if x==2:
    print('two')
if x==3:
    print('three')

one


In [25]:
x=3

if x==1:
    print('one')
if x==2:
    print('two')
if x==3:
    print('three')

three


In [26]:
x=6

if x==1:
    print('one')
if x==2:
    print('two')
if x==3:
    print('three')

In [27]:
x=3
r=x%2

if r==0:
    print('even number')
    if x>5:
        print('greater number')
else :
    print('odd number')

odd number


In [28]:
x=4
r=x%2

if r==0:
    print('even number')
    if x>5:
        print('greater number')
else :
    print('odd number')

even number


In [29]:
x=6
r=x%2

if r==0:
    print('even number')
    if x>5:
        print('greater number')
else :
    print('odd number')

even number
greater number


In [31]:
x=7
r=x%2

if r==0:
    print('even number')
    if x>5:
        print('greater number')
else :
    print('odd number')

odd number


In [37]:
x = 4
r = x % 2

if r == 0:
    print('Even number')
    
    if x>5:
        print('greater number')

    
    else:
        print('number is lesser number')
  
else:
    print('Odd Number')

Even number
number is lesser number


In [38]:
x = 5
r = x % 2

if r == 0:
    print('Even number')
    
    if x>5:
        print('greater number')

    
    else:
        print('number is lesser number')
  
else:
    print('Odd Number')

Odd Number


In [39]:
x = 6
r = x % 2

if r == 0:
    print('Even number')
    
    if x>5:
        print('greater number')

    
    else:
        print('number is lesser number')
  
else:
    print('Odd Number') 

Even number
greater number


In [40]:
x = 7
r = x % 2

if r == 0:
    print('Even number')
    
    if x>5:
        print('greater number')

    
    else:
        print('number is lesser number')
  
else:
    print('Odd Number')

Odd Number


In [41]:
x = 4

if(x == 1):
    print('one')
elif(x == 2):
    print('Two')
elif(x == 3):
    print('Three')
elif(x == 4):
    print('four')

four


In [42]:
x = 3

if(x == 1):
    print('one')
elif(x == 2):
    print('Two')
elif(x == 3):
    print('Three')
elif(x == 4):
    print('four')

Three


In [43]:
x = 1

if(x == 1):
    print('one')
elif(x == 2):
    print('Two')
elif(x == 3):
    print('Three')
elif(x == 4):
    print('four')

one


In [44]:
x = 7

if(x == 1):
    print('one')
elif(x == 2):
    print('Two')
elif(x == 3):
    print('Three')
elif(x == 4):
    print('four')

In [45]:
x = 7

if(x == 1):
    print('one')
elif(x == 2):
    print('Two')
elif(x == 3):
    print('Three')
elif(x == 4):
    print('four')
else:
    print('number not found')

number not found


#Loops

In [48]:
i=1
while i<=5:
    print('Hello')
    i=i+1

Hello
Hello
Hello
Hello
Hello


In [1]:
i=1

while i<=5:
    print('data science')
    j=1
    while j<=4:
        print('technology')
        j= j + 1
    
    
    i= i + 1
    print()

data science
technology
technology
technology
technology

data science
technology
technology
technology
technology

data science
technology
technology
technology
technology

data science
technology
technology
technology
technology

data science
technology
technology
technology
technology



In [5]:
i=1

while i<=5:
    print('data science',end="")
    j=1
    while j<=4:
        
        print('technology',end="")
        j= j + 1
    
    
    i= i + 1
    print()

data sciencetechnologytechnologytechnologytechnology
data sciencetechnologytechnologytechnologytechnology
data sciencetechnologytechnologytechnologytechnology
data sciencetechnologytechnologytechnologytechnology
data sciencetechnologytechnologytechnologytechnology


In [6]:
i=1

while i<=5:
    print('data science',end="")
    j=1
    while j<=4:
        
        print(' technology',end="")
        j= j + 1
    
    
    i= i + 1
    print()

data science technology technology technology technology
data science technology technology technology technology
data science technology technology technology technology
data science technology technology technology technology
data science technology technology technology technology


In [1]:
i=1

while i<=2:
    j=0
    while j<=2:
        print(i*j,end="  ")
        j=j+1
    print()
    i+=1    

0  1  2  
0  2  4  


In [3]:
i=1

while i<=4:
    j=0
    while j<=3:
        print(i*j,end="  ")
        j=j+1
    i+=1
    print()

0  1  2  3  
0  2  4  6  
0  3  6  9  
0  4  8  12  


In [ ]:
FOR LOOP  -
normally while loop it work with iteration or certaion some condition but 
for loop it will work with sequence (list, string,int)

In [4]:
name='nit'

for i in name:
    print(i)

n
i
t


In [5]:
name1=[1,2,34,'f','u']

for i in name1:
    print(i)

1
2
34
f
u


In [6]:
name2=(1,2,3,4,'f','uy')

for i in name2:
    print(i)

1
2
3
4
f
uy


In [7]:
name3={1,2,3,4,'sd','wr'}

for i in name3:
    print(i)

1
2
3
4
wr
sd


In [ ]:
name4={'name':'nit','city':'pune','course':'data science'}
for i in name4:
    print(i)

name
city
course


In [11]:
name4={'name':'nit','city':'pune','course':'data science'}
for i in name4.values():
    print(i)

nit
pune
data science


In [12]:
for i in(1,2,3):
    print(i)


1
2
3


In [13]:
for i in {1:'A',2:'B'}:
    print(i)

1
2


In [14]:
for i in {1:'A',2:'B'}.values():
    print(i)

A
B


In [15]:
for i in range(5):
    print(i)

0
1
2
3
4


In [16]:
for i in range(2,5):
    print(i)

2
3
4


In [17]:
for i in range(1,10,5):
    print(i)

1
6


In [18]:
a=['nit','pune',1996,2000,2,3,4,54,3.56,True]
for i in a[2:6]:
    print(i)

1996
2000
2
3


In [21]:
a=['nit','pune',1996,2000,2,3,4,54,3.56,True]
for i in str(a[3]):
    print(i)

2
0
0
0


In [24]:
a=['nit','pune',1996,2000,2,3,4,54,3.56,True]
for i in str(a[3], ):
    print(i,end="")

2000

In [25]:
for i in range(1,51):
    if i%5==0:
        print(i)

5
10
15
20
25
30
35
40
45
50


In [26]:
for i in range(1,51):
    if i%3==0 and i%5==0:
        print(i)

15
30
45


In [27]:
for i in range(1,51):
    if i%3==0 or i%5==0:
        print(i)

3
5
6
9
10
12
15
18
20
21
24
25
27
30
33
35
36
39
40
42
45
48
50


In [32]:
x=int(input('How many chocolates you want?'))

i = 1
while i<=x:
    print('chocolate')
    i += 1

chocolate
chocolate
chocolate
chocolate
chocolate


In [33]:
avg=5

x=int(input('How many chocolates you want?'))

i = 1
while i<=x:
    print('chocolate')
    i += 1


chocolate
chocolate
chocolate
chocolate
chocolate
chocolate
chocolate
chocolate
chocolate
chocolate


In [42]:
avg = 5
x=int(input('How many chocolates you want?'))

i=1
while i<=x:
    
    if i>avg:
        break
    print('chocalate')
    i += 1
    
print('bye for now')

chocalate
chocalate
chocalate
chocalate
bye for now


In [50]:
available=5

x=int(input('How many chocolates you want?'))

i=1
while i<=x:
    
    if i>available:
        print('sorry not available')
        break
    print('chocalate')
    i += 1
print('bye for now')

chocalate
chocalate
chocalate
chocalate
chocalate
sorry not available
bye for now


In [53]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [56]:
for i in range(1,11):
    if i==6:
        break
    print(i)

1
2
3
4
5


In [57]:
for i in range(1,11):
    if i==6:
        continue
    print(i)

1
2
3
4
5
7
8
9
10


In [59]:
for i in range(1,11):
    if i==6:
        continue
    print('hellow:',i)

hellow: 1
hellow: 2
hellow: 3
hellow: 4
hellow: 5
hellow: 7
hellow: 8
hellow: 9
hellow: 10


In [60]:
for i in range(1,11):

_IncompleteInputError: incomplete input (1334445784.py, line 1)

In [61]:
for i in range(1,11):
    pass

In [62]:
for i in range(1,50):
    if i%3==0:
        print(i)

3
6
9
12
15
18
21
24
27
30
33
36
39
42
45
48


In [72]:
for i in range(1,51):
    if i%3 == 0:
        continue
    print(i)


1
2
4
5
7
8
10
11
13
14
16
17
19
20
22
23
25
26
28
29
31
32
34
35
37
38
40
41
43
44
46
47
49
50


In [74]:
for i in range(1,5):
    
    i=i+1
    print('****')

****
****
****
****


In [76]:
for i in range(1,5):
    print('#')

#
#
#
#


In [78]:
for i in range(1,5):
    print('####', end="  ")

####  ####  ####  ####  

In [80]:
for j in range(4):
    print('####', end="  ")
    
for j in range(4):
    print('####', end="  ")
    
    

####  ####  ####  ####  ####  ####  ####  ####  

In [81]:
for j in range(4):
    print('##', end="  ")
    
print()

for j in range(4):
    print('##', end="  ")

##  ##  ##  ##  
##  ##  ##  ##  

In [82]:
for i in range(4):
    for j in range(4):
        print('#', end="  ")
    print()

#  #  #  #  
#  #  #  #  
#  #  #  #  
#  #  #  #  


In [94]:
for i in range(4):
    for j in range(i+1):
        print('#', end="  ")
    print()

#  
#  #  
#  #  #  
#  #  #  #  


In [99]:
for i in range(1,5):
    print("# " *i)

# 
# # 
# # # 
# # # # 


In [104]:
for i in range(1,4):
    for j in range(4):
        i<j
        print('#', end="  ")
    print()

#  #  #  #  
#  #  #  #  
#  #  #  #  


In [105]:
list(range(5))

[0, 1, 2, 3, 4]

In [106]:
for i in range(5):
    for j in range(i):
        print('#', end="  ")
    print()


#  
#  #  
#  #  #  
#  #  #  #  


In [111]:
for i in range(5):
    for j in range(i):
        print('#', end="  ")
    print()


#  
#  #  
#  #  #  
#  #  #  #  


In [109]:
range(5,1)

range(5, 1)

In [113]:
for i in range(4):
    for j in range(4-i):
        print('#', end="  ")
    print()

#  #  #  #  
#  #  #  
#  #  
#  


In [117]:
for i in range(1,5):
    print('# '*(5-i))

# # # # 
# # # 
# # 
# 


In [123]:
nums=[1,2,3,24,423,24,432534,6566,65,32]

for num in nums:
    if num%2==0:
        print(num)
    

2
24
24
432534
6566
32


In [127]:
nums=[12,2,35,2,3]

for num in nums:
    if num%5==0:
        print(num)
        break

35


In [130]:
x=[12,32,24,42,566]

for y in x:
    if y%5==0:
        print(y)
        break
else:
        print('not found')

not found


In [131]:
a=[2,3,3,5354,654,33,26]

for b in a:
    if b%5==0:
        print(b)
        break
    else:
        print('not found')

not found
not found
not found
not found
not found
not found
not found


In [144]:
a=[2,3,3,5354,654,33,26]

for b in a:
    if b%5==0:
        print(b)
        break
else:
     print('not found')

not found


In [146]:

a=[7,3,3,5354,654,33,26]

for b in a:
    if b%2==0:
        print(b)
        break
else:
     print('not found')

5354


In [148]:
a=[2,3,3,5354,654,33,26]

for b in a:
    if b%2==0:
        print(b)
        
else:
     print('not found')

2
5354
654
26
not found


In [166]:
a=14

for i in range(2,a):
    if a % i == 0:
        print('not prime')
        break
else:
     print('prime')

not prime


In [167]:
a=int(input('enter a number:'))

for i in range(2,a):
    if a % i == 0:
        print('not prime')
        break
else:
     print('prime')

not prime


In [168]:
from array import *
arr=array('i',[])
n=int(input('enter length of array:'))
 
for i in range(5):
    x=int(input('enter next value:'))
    arr.append(x)
print(arr)

array('i', [4, 2, 3, 3, 2])


In [169]:
from numpy import *
arr=array([1,2,3,4,5])  
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [170]:
print(arr.dtype)

int64


In [172]:
import numpy as np

In [173]:
arr=np.linspace(0,15,10)
print(arr)

[ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.         11.66666667 13.33333333 15.        ]


In [175]:
x=np.arange(1,15,2)
x

array([ 1,  3,  5,  7,  9, 11, 13])

In [177]:
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [178]:
b=np.ones(5)
b

array([1., 1., 1., 1., 1.])